### PR TITLE
feat(derive): Holocene Reset Type

### LINKED ISSUE #556: [TRACKING] Holocene Hardfork Changes
### Description

> [!WARNING]
>
> It is highly encouraged to [read the specs](https://specs.optimism.io/protocol/holocene/overview.html) prior to working on this implementation.

This is a tracking issue for [Holocene Hardfork](https://specs.optimism.io/protocol/holocene/overview.html) changes to kona and its dependency set.

### PR DESCRIPTION
**Pull request by refcell**
### Description

Refactors stage resets into a type to easily slot in a new Holocene hardfork reset type.

Closes #556

### CODE REVIEW

**Comment by refcell** [comment]
* **#565** <a href="https://app.graphite.dev/github/pr/anton-rs/kona/565?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @refcell and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by refcell** [comment]
When someone asks me what my refactors look like:
Screenshot 2024-09-24 at 12 55 15 PM

**Review by clabby — CHANGES_REQUESTED** [review]
I think we can slim this down a lot if we instead just add a new `ResetError` variant for the holocene fork activation. The driver already accepts reset errors for stages to be able to force pipeline resets, and the in-memory `holocene_reset` flag is also going to cause some bugs I think on restarts, since it doesn't get reset on reboot.

In `L1Traversal`, when the origin gets advanced, we can compare the old origin timestamp to the new origin timestamp to see if the pipeline needs to be reset. If the old origin's timestamp is granite, and the new one is >= holocene, we can throw a `ResetError::HoloceneActivated`

**Comment by refcell** [comment]
Replaced by #574 :))

**Pull request closed without merging**
